language: julia

os:
  - linux

branches:
  only:
  - master
  
julia:
  - 0.5

notifications:
  email: false

after_success:
  - julia -e 'cd(Pkg.dir("LARLIB")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
